sonar.organization=felipeschirmann
sonar.projectKey=felipeschirmann_DSMeta
sonar.projectName=DSMeta
sonar.host.url=https://sonarcloud.io

# Define sources, tests and exclusions
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src
sonar.test.inclusions=backend/src/test/java/**/*.java,frontend/src/**/*.test.tsx,frontend/src/**/*.test.ts,frontend/src/setupTests.ts
sonar.exclusions=frontend/node_modules/**,frontend/build/**,**/target/**,frontend/src/**/*.test.tsx,frontend/src/**/*.test.ts,frontend/src/setupTests.ts

# Java specific configuration
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

# Code coverage exclusions (excluding boilerplate java and non-testable CSS files)
sonar.coverage.exclusions=backend/src/main/java/com/devsuperior/dsmeta/config/**,backend/src/main/java/com/devsuperior/dsmeta/dto/**,backend/src/main/java/com/devsuperior/dsmeta/entities/**,backend/src/main/java/com/devsuperior/dsmeta/DsmetaApplication.java,backend/src/main/java/com/devsuperior/dsmeta/ServletInitializer.java,**/*.css

# JavaScript/TypeScript coverage report path
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
