services:
  db:
    container_name: dsmeta-pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_local_password
      POSTGRES_DB: dsmeta
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: dsmeta-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@pgadm.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
