name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true    
  push:
    branches:
      - "main"
    paths:
      - "backend/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 18
      - name: Move files backend to .
        run: mv -f backend/* .
      - name: Remove frontend
        run: rm -rf frontend/
      - name: Build with Maven
        run: mvn clean install
        env:
          TWILIO_KEY: ${{ secrets.TWILIO_KEY }}
          TWILIO_PHONE_FROM: ${{ secrets.TWILIO_PHONE_FROM }}
          TWILIO_PHONE_TO: ${{ secrets.TWILIO_PHONE_TO }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: felipeschirmann/ds-meta
          tags: ${{github.run_number}},latest
