name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '!backend/**/*.md'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '!backend/**/*.md'
      - '.github/workflows/ci.yml'

jobs:
  build-and-test:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and Test Backend
        run: |
          mvn -f backend/pom.xml -B verify

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -f backend/pom.xml -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=felipeschirmann_DSMeta -Dsonar.organization=felipeschirmann
