name: ci

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true  
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
            distribution: 'temurin'
            java-version: 18
      - name: Move files backend to .
        run: mv -f backend/* . 
      - name: Remove frontend
        run: rm -rf frontend/
      - name: Build with Maven
        run: mvn clean install
        env:
          TWILIO_KEY: ${{ secrets.TWILIO_KEY }}
          TWILIO_PHONE_FROM: ${{ secrets.TWILIO_PHONE_FROM }}
          TWILIO_PHONE_TO: ${{ secrets.TWILIO_PHONE_TO }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ds-meta:${{github.run_number}},${{ secrets.DOCKER_HUB_USERNAME }}/ds-meta:latest